/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type {
  DiscreteEvolutionRequest,
  DiscreteEvolutionResponse,
  EigenstatesRequest,
  EigenstatesResponse,
  HTTPValidationError,
  MeasurementRequest,
  MeasurementResponse,
  SeparableStateRequest,
  SeparableStateResponse,
  SingleAtomStateRequest,
  SingleAtomStateResponse,
  TrajectoryRequest,
  TrajectoryResponse
} from '.././schemas';

import { customFetch } from '../../http';

/**
 * Solve the time-independent Schrödinger equation and return eigenstates.

Accepts either a named potential (Option A) or a custom V(x) array (Option B).
 * @summary Eigenstates
 */
export type eigenstatesV1QmEigenstatesPostResponse200 = {
  data: EigenstatesResponse
  status: 200
}

export type eigenstatesV1QmEigenstatesPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type eigenstatesV1QmEigenstatesPostResponseSuccess = (eigenstatesV1QmEigenstatesPostResponse200) & {
  headers: Headers;
};
export type eigenstatesV1QmEigenstatesPostResponseError = (eigenstatesV1QmEigenstatesPostResponse422) & {
  headers: Headers;
};

export type eigenstatesV1QmEigenstatesPostResponse = (eigenstatesV1QmEigenstatesPostResponseSuccess | eigenstatesV1QmEigenstatesPostResponseError)

export const getEigenstatesV1QmEigenstatesPostUrl = () => {


  

  return `/v1/qm/eigenstates`
}

export const eigenstatesV1QmEigenstatesPost = async (eigenstatesRequest: EigenstatesRequest, options?: RequestInit): Promise<eigenstatesV1QmEigenstatesPostResponse> => {
  
  return customFetch<eigenstatesV1QmEigenstatesPostResponse>(getEigenstatesV1QmEigenstatesPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      eigenstatesRequest,)
  }
);}


/**
 * One eigenstate of a system that separates along x and y.

The potential is given per axis, so `infinite_well` on both axes is a
particle in a 2D box, `harmonic` on both is a 2D trap, and the axes may
differ. Each axis is solved analytically when its potential has a known
solution and numerically otherwise; the state is the product of the two.
 * @summary Separable State
 */
export type separableStateV1QmSeparableStatePostResponse200 = {
  data: SeparableStateResponse
  status: 200
}

export type separableStateV1QmSeparableStatePostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type separableStateV1QmSeparableStatePostResponseSuccess = (separableStateV1QmSeparableStatePostResponse200) & {
  headers: Headers;
};
export type separableStateV1QmSeparableStatePostResponseError = (separableStateV1QmSeparableStatePostResponse422) & {
  headers: Headers;
};

export type separableStateV1QmSeparableStatePostResponse = (separableStateV1QmSeparableStatePostResponseSuccess | separableStateV1QmSeparableStatePostResponseError)

export const getSeparableStateV1QmSeparableStatePostUrl = () => {


  

  return `/v1/qm/separable-state`
}

export const separableStateV1QmSeparableStatePost = async (separableStateRequest: SeparableStateRequest, options?: RequestInit): Promise<separableStateV1QmSeparableStatePostResponse> => {
  
  return customFetch<separableStateV1QmSeparableStatePostResponse>(getSeparableStateV1QmSeparableStatePostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      separableStateRequest,)
  }
);}


/**
 * Compute the single-atom state for a given potential and quantum numbers.

Accepts either a named potential (Option A) or a custom V(x) array (Option B).
 * @summary Single Atom State
 */
export type singleAtomStateV1QmSingleAtomStatePostResponse200 = {
  data: SingleAtomStateResponse
  status: 200
}

export type singleAtomStateV1QmSingleAtomStatePostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type singleAtomStateV1QmSingleAtomStatePostResponseSuccess = (singleAtomStateV1QmSingleAtomStatePostResponse200) & {
  headers: Headers;
};
export type singleAtomStateV1QmSingleAtomStatePostResponseError = (singleAtomStateV1QmSingleAtomStatePostResponse422) & {
  headers: Headers;
};

export type singleAtomStateV1QmSingleAtomStatePostResponse = (singleAtomStateV1QmSingleAtomStatePostResponseSuccess | singleAtomStateV1QmSingleAtomStatePostResponseError)

export const getSingleAtomStateV1QmSingleAtomStatePostUrl = () => {


  

  return `/v1/qm/single-atom-state`
}

export const singleAtomStateV1QmSingleAtomStatePost = async (singleAtomStateRequest: SingleAtomStateRequest, options?: RequestInit): Promise<singleAtomStateV1QmSingleAtomStatePostResponse> => {
  
  return customFetch<singleAtomStateV1QmSingleAtomStatePostResponse>(getSingleAtomStateV1QmSingleAtomStatePostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      singleAtomStateRequest,)
  }
);}


/**
 * Measure a Hermitian observable on a state of a discrete Hilbert space.

Returns one entry per *distinct* eigenvalue — its Born probability and the
state the measurement collapses to — so a degenerate eigenvalue appears
once, with its probability summed over the whole eigenspace. Those
probabilities are exact; `n_draws` additionally samples that distribution
and reports how many draws landed on each outcome.
 * @summary Discrete Measurement
 */
export type discreteMeasurementV1QmDiscreteMeasurementPostResponse200 = {
  data: MeasurementResponse
  status: 200
}

export type discreteMeasurementV1QmDiscreteMeasurementPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type discreteMeasurementV1QmDiscreteMeasurementPostResponseSuccess = (discreteMeasurementV1QmDiscreteMeasurementPostResponse200) & {
  headers: Headers;
};
export type discreteMeasurementV1QmDiscreteMeasurementPostResponseError = (discreteMeasurementV1QmDiscreteMeasurementPostResponse422) & {
  headers: Headers;
};

export type discreteMeasurementV1QmDiscreteMeasurementPostResponse = (discreteMeasurementV1QmDiscreteMeasurementPostResponseSuccess | discreteMeasurementV1QmDiscreteMeasurementPostResponseError)

export const getDiscreteMeasurementV1QmDiscreteMeasurementPostUrl = () => {


  

  return `/v1/qm/discrete-measurement`
}

export const discreteMeasurementV1QmDiscreteMeasurementPost = async (measurementRequest: MeasurementRequest, options?: RequestInit): Promise<discreteMeasurementV1QmDiscreteMeasurementPostResponse> => {
  
  return customFetch<discreteMeasurementV1QmDiscreteMeasurementPostResponse>(getDiscreteMeasurementV1QmDiscreteMeasurementPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      measurementRequest,)
  }
);}


/**
 * Evolve a state on a finite Hilbert space, reported in the energy eigenbasis.

Returns c_n(t) = <E_n|psi(t)> at every frame, alongside the energies those
coefficients belong to. Each one keeps its modulus and turns at its own
rate, c_n(t) = c_n(0) exp(-i E_n t) — the whole content of the Schrödinger
equation once the eigenproblem is solved.

`reference` additionally projects psi(t) onto a fixed state; with the
all-ones vector that is the sum of the amplitudes, which is what adding
the individual phasors up gives.
 * @summary Discrete Evolution
 */
export type discreteEvolutionV1QmDiscreteEvolutionPostResponse200 = {
  data: DiscreteEvolutionResponse
  status: 200
}

export type discreteEvolutionV1QmDiscreteEvolutionPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type discreteEvolutionV1QmDiscreteEvolutionPostResponseSuccess = (discreteEvolutionV1QmDiscreteEvolutionPostResponse200) & {
  headers: Headers;
};
export type discreteEvolutionV1QmDiscreteEvolutionPostResponseError = (discreteEvolutionV1QmDiscreteEvolutionPostResponse422) & {
  headers: Headers;
};

export type discreteEvolutionV1QmDiscreteEvolutionPostResponse = (discreteEvolutionV1QmDiscreteEvolutionPostResponseSuccess | discreteEvolutionV1QmDiscreteEvolutionPostResponseError)

export const getDiscreteEvolutionV1QmDiscreteEvolutionPostUrl = () => {


  

  return `/v1/qm/discrete-evolution`
}

export const discreteEvolutionV1QmDiscreteEvolutionPost = async (discreteEvolutionRequest: DiscreteEvolutionRequest, options?: RequestInit): Promise<discreteEvolutionV1QmDiscreteEvolutionPostResponse> => {
  
  return customFetch<discreteEvolutionV1QmDiscreteEvolutionPostResponse>(getDiscreteEvolutionV1QmDiscreteEvolutionPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      discreteEvolutionRequest,)
  }
);}


/**
 * Track where a wavepacket is over time.

Returns <x>(t) and <p>(t) with their spreads, alongside the path a
classical point particle would take from the same starting conditions.
In a harmonic well the two positions coincide exactly (Ehrenfest's
theorem, the force being linear); anywhere else the gap between them is
the part of the motion that has no classical counterpart.
 * @summary Trajectory
 */
export type trajectoryV1QmTrajectoryPostResponse200 = {
  data: TrajectoryResponse
  status: 200
}

export type trajectoryV1QmTrajectoryPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type trajectoryV1QmTrajectoryPostResponseSuccess = (trajectoryV1QmTrajectoryPostResponse200) & {
  headers: Headers;
};
export type trajectoryV1QmTrajectoryPostResponseError = (trajectoryV1QmTrajectoryPostResponse422) & {
  headers: Headers;
};

export type trajectoryV1QmTrajectoryPostResponse = (trajectoryV1QmTrajectoryPostResponseSuccess | trajectoryV1QmTrajectoryPostResponseError)

export const getTrajectoryV1QmTrajectoryPostUrl = () => {


  

  return `/v1/qm/trajectory`
}

export const trajectoryV1QmTrajectoryPost = async (trajectoryRequest: TrajectoryRequest, options?: RequestInit): Promise<trajectoryV1QmTrajectoryPostResponse> => {
  
  return customFetch<trajectoryV1QmTrajectoryPostResponse>(getTrajectoryV1QmTrajectoryPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      trajectoryRequest,)
  }
);}


