/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */

export interface CoexistenceResponse {
  temperatures: number[];
  /** mu_c, kelvin */
  chemical_potential: number[];
  /** sublimation pressure, pascals */
  pressure: number[];
  /** eps_c - 3 hbar omega / 2, kelvin */
  latent_heat: number;
}
