/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { TemperatureRange } from './temperatureRange';

/**
 * Solid-gas equilibrium: an Einstein crystal against an ideal gas.

Defaults are argon: `hbar omega / k_B = 90 K`, and a cohesion energy equal
to the measured sublimation enthalpy plus the zero point the atom is given
back, since the slope of `log P` against `1/T` is `eps_c - 3 hbar omega/2`.
 */
export interface CoexistenceRequest {
  /**
   * hbar omega / k_B, kelvin
   */
  omega?: number;
  /**
   * eps_c / k_B, kelvin
   */
  cohesion?: number;
  /** */
  mass_amu?: number;
  temperatures?: TemperatureRange;
}
