/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { ComplexVectorSchemaIm } from './complexVectorSchemaIm';

/**
 * A complex vector: v[k] = re[k] + 1j * im[k].
 */
export interface ComplexVectorSchema {
  /** Real parts, one per coefficient */
  re: number[];
  /** Imaginary parts. Omit for a real vector. */
  im?: ComplexVectorSchemaIm;
}
