/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { ComplexMatrixSchemaIm } from './complexMatrixSchemaIm';

/**
 * A complex square matrix, row-major: M[i][j] = re[i][j] + 1j * im[i][j].
 */
export interface ComplexMatrixSchema {
  /** Real parts, row-major */
  re: number[][];
  /** Imaginary parts, row-major. Omit for a real matrix. */
  im?: ComplexMatrixSchemaIm;
}
