/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { ComplexMatrixSchema } from './complexMatrixSchema';
import type { ComplexVectorSchema } from './complexVectorSchema';
import type { DiscreteEvolutionRequestReference } from './discreteEvolutionRequestReference';

/**
 * Evolution of a state on a finite-dimensional Hilbert space.

A finite H is diagonalised rather than stepped, so every frame is computed
from psi(0) directly: no time step, no accumulating error, and the cost of
a long run is the cost of a short one.
 */
export interface DiscreteEvolutionRequest {
  /** Hermitian Hamiltonian in the computational basis (hbar = 1) */
  hamiltonian: ComplexMatrixSchema;
  /** Initial state psi(0), computational basis. Normalised server-side. */
  state: ComplexVectorSchema;
  /**
   * Length of the run, in atomic units. The frames span [0, t_max) with the endpoint excluded, so a run whose t_max is a recurrence time of the spectrum can be played on a loop without a repeated frame at the seam.
   * @maximum 1000
   */
  t_max?: number;
  /**
   * Frames to return
   * @minimum 2
   * @maximum 1024
   */
  n_frames?: number;
  /** A fixed state to project psi(t) onto, in the computational basis. Its amplitude comes back in `overlap`. Not normalised, so passing the all-ones vector gives the plain sum of the amplitudes. */
  reference?: DiscreteEvolutionRequestReference;
}
