/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { ComplexVectorSchema } from './complexVectorSchema';
import type { DiscreteEvolutionResponseOverlap } from './discreteEvolutionResponseOverlap';

/**
 * The state at every frame, read in the energy eigenbasis.

Only the phases move: |c_n| is fixed by psi(0) and conserved for as long
as H is, which is what makes the energy distribution of a state a constant
of the motion.
 */
export interface DiscreteEvolutionResponse {
  times: number[];
  /** Eigenvalues of the Hamiltonian, ascending — the E_n of the c_n */
  energies: number[];
  /** c_n(t) = <E_n|psi(t)>, one vector per time, its entries ordered by ascending energy to match `energies`. */
  coefficients: ComplexVectorSchema[];
  /** <reference|psi(t)>, as a complex series over `times` rather than a state — one entry per frame. None unless `reference` was given. */
  overlap?: DiscreteEvolutionResponseOverlap;
}
