/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { ComplexVectorSchema } from './complexVectorSchema';

/**
 * <reference|psi(t)>, as a complex series over `times` rather than a state — one entry per frame. None unless `reference` was given.
 */
export type DiscreteEvolutionResponseOverlap = ComplexVectorSchema | null;
