/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { ComplexVectorSchema } from './complexVectorSchema';

/**
 * A fixed state to project psi(t) onto, in the computational basis. Its amplitude comes back in `overlap`. Not normalised, so passing the all-ones vector gives the plain sum of the amplitudes.
 */
export type DiscreteEvolutionRequestReference = ComplexVectorSchema | null;
