/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { GridSchema } from './gridSchema';
import type { PotentialSchema } from './potentialSchema';

export interface EigenstatesRequest {
  grid?: GridSchema;
  potential: PotentialSchema;
  /**
   * @minimum 1
   * @maximum 20
   */
  n_states?: number;
}
