/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { GasRequestSeed } from './gasRequestSeed';

/**
 * A Monte Carlo gas of spin-`s` particles in a periodic cubic box.

The spin fixes both halves: `2s+1` states per orbital, and half-integer
spin means fermions while integer spin means bosons. That is the
spin-statistics theorem doing the dispatch rather than the caller being
asked the same fact twice.
 */
export interface GasRequest {
  /**
   * box edge, nanometres
   */
  box?: number;
  /**
   * @minimum 1
   * @maximum 400
   */
  particles?: number;
  /**
   * @minimum 0
   * @maximum 3
   */
  spin?: number;
  /**
   * kelvin
   */
  temperature?: number;
  /**
   * @minimum 100
   * @maximum 20000
   */
  samples?: number;
  /**
   * @minimum 0
   * @maximum 5000
   */
  burn_in_sweeps?: number;
  seed?: GasRequestSeed;
}
