/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */

/**
 * Sampled occupations, and the closed form they are checked against.

`chemical_potential_fitted` is what the simulation alone can give: a least
squares fit of the distribution to the measured occupations. It is
reported beside the exact value so the two can be compared rather than one
standing in for the other.
 */
export interface GasResponse {
  /** distinct orbital energies, kelvin */
  energies: number[];
  occupation: number[];
  occupation_error: number[];
  /** closed form at the exact mu */
  distribution: number[];
  statistics: string;
  fermi_temperature: number;
  chemical_potential_fitted: number;
  chemical_potential_error: number;
  chemical_potential_exact: number;
  orbitals: number;
  acceptance: number;
}
