/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */

/**
 * the classical limit, fermions only
 */
export type GasSweepPointMaxwellBoltzmann = number | null;
