/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { GasSweepPointSommerfeld } from './gasSweepPointSommerfeld';
import type { GasSweepPointMaxwellBoltzmann } from './gasSweepPointMaxwellBoltzmann';

export interface GasSweepPoint {
  temperature: number;
  particles: number;
  fermi_temperature: number;
  chemical_potential_fitted: number;
  chemical_potential_error: number;
  chemical_potential_exact: number;
  /** Ef[1 - (pi^2/12)(T/Tf)^2], fermions only */
  sommerfeld?: GasSweepPointSommerfeld;
  /** the classical limit, fermions only */
  maxwell_boltzmann?: GasSweepPointMaxwellBoltzmann;
}
