/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */

/**
 * Ef[1 - (pi^2/12)(T/Tf)^2], fermions only
 */
export type GasSweepPointSommerfeld = number | null;
