/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */

export type GasSweepRequestVary = typeof GasSweepRequestVary[keyof typeof GasSweepRequestVary];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GasSweepRequestVary = {
  temperature: 'temperature',
  particles: 'particles',
} as const;
