/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { GasSweepRequestVary } from './gasSweepRequestVary';
import type { GasSweepRequestSeed } from './gasSweepRequestSeed';

/**
 * Many converged chains, one per value of the swept parameter.

`vary` picks which axis: temperature at fixed particle number, or particle
number at fixed temperature. Points are independent, so they run in
parallel processes.
 */
export interface GasSweepRequest {
  /**
   * box edge, nanometres
   */
  box?: number;
  /**
   * @minimum 0
   * @maximum 3
   */
  spin?: number;
  vary?: GasSweepRequestVary;
  /**
   * @minItems 1
   * @maxItems 24
   */
  values: number[];
  /**
   * fixed when varying T
   * @minimum 1
   * @maximum 400
   */
  particles?: number;
  /**
   * fixed when varying N
   */
  temperature?: number;
  /**
   * @minimum 100
   * @maximum 8000
   */
  samples?: number;
  /**
   * @minimum 0
   * @maximum 5000
   */
  burn_in_sweeps?: number;
  seed?: GasSweepRequestSeed;
}
