/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */

export interface Grid2DSchema {
  x_min?: number;
  x_max?: number;
  y_min?: number;
  y_max?: number;
  /**
   * @minimum 64
   * @maximum 2048
   */
  nx?: number;
  /**
   * @minimum 64
   * @maximum 2048
   */
  ny?: number;
}
