/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */

/**
 * One signed isosurface shell as a triangle mesh, packed for direct upload to
a WebGL BufferGeometry. Each string is base64 of the little-endian raw
bytes: positions/normals are flat float32 [x,y,z,...]; indices are flat
uint32 triangle vertex indices.
 */
export interface LobeMeshSchema {
  positions: string;
  normals: string;
  indices: string;
  vertex_count: number;
  triangle_count: number;
}
