/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */

/**
 * Number of measurements to sample, for showing shot noise against the exact probabilities. Omit to skip sampling; the outcomes themselves are the same either way.
 */
export type MeasurementRequestNDraws = number | null;
