/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { ComplexVectorSchema } from './complexVectorSchema';
import type { ComplexMatrixSchema } from './complexMatrixSchema';
import type { MeasurementRequestNDraws } from './measurementRequestNDraws';
import type { MeasurementRequestSeed } from './measurementRequestSeed';

/**
 * A projective measurement of `operator` on `state`.

The operator must be Hermitian; its eigenvalues are the possible outcomes.
 */
export interface MeasurementRequest {
  /** State in the computational basis. Normalised server-side. */
  state: ComplexVectorSchema;
  /** Hermitian observable in the computational basis */
  operator: ComplexMatrixSchema;
  /** Number of measurements to sample, for showing shot noise against the exact probabilities. Omit to skip sampling; the outcomes themselves are the same either way. */
  n_draws?: MeasurementRequestNDraws;
  /** Seed for the draws, to make them reproducible */
  seed?: MeasurementRequestSeed;
}
