/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { OutcomeSchema } from './outcomeSchema';
import type { MeasurementResponseNDraws } from './measurementResponseNDraws';

export interface MeasurementResponse {
  /** One entry per distinct eigenvalue, ascending in value */
  outcomes: OutcomeSchema[];
  /** Number of draws sampled, echoed back */
  n_draws?: MeasurementResponseNDraws;
}
