/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */

/**
 * Draws that gave this outcome. None unless n_draws was set.
 */
export type OutcomeSchemaCount = number | null;
