/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { OutcomeSchemaState } from './outcomeSchemaState';
import type { OutcomeSchemaCount } from './outcomeSchemaCount';

/**
 * One distinct eigenvalue, and what measuring it does to the state.

A degenerate eigenvalue appears once, with its probability summed over the
whole eigenspace and `state` the projection onto that subspace — not onto
any single eigenvector.
 */
export interface OutcomeSchema {
  /** The eigenvalue observed */
  value: number;
  /** Born probability, summed over the eigenspace */
  probability: number;
  /** Dimension of the eigenspace for this value */
  degeneracy: number;
  /** Normalised post-measurement state, None where the probability is zero and the collapse is undefined. */
  state: OutcomeSchemaState;
  /** Draws that gave this outcome. None unless n_draws was set. */
  count?: OutcomeSchemaCount;
}
