/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { ComplexVectorSchema } from './complexVectorSchema';

/**
 * Normalised post-measurement state, None where the probability is zero and the collapse is undefined.
 */
export type OutcomeSchemaState = ComplexVectorSchema | null;
