/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */

/**
 * Custom V(x) values, one per grid point (Option B)
 */
export type PotentialSchemaValues = number[] | null;
