/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { HarmonicParams } from './harmonicParams';
import type { InfiniteWellParams } from './infiniteWellParams';
import type { FiniteWellParams } from './finiteWellParams';
import type { BarrierParams } from './barrierParams';
import type { StepParams } from './stepParams';
import type { DoubleWellParams } from './doubleWellParams';

export type PotentialSchemaParams = HarmonicParams | InfiniteWellParams | FiniteWellParams | BarrierParams | StepParams | DoubleWellParams | null;
