/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */

/**
 * The state as its two one-dimensional factors: psi(x, y) = psi_x(x) * psi_y(y).

Sending the factors rather than the (nx, ny) field keeps the payload
proportional to nx + ny instead of nx * ny; the client reconstructs the
field with an outer product.
 */
export interface SeparableStateResponse {
  x: number[];
  y: number[];
  /** Normalised factor along x */
  psi_x: number[];
  /** Normalised factor along y */
  psi_y: number[];
  /** V(x) sampled on the x axis */
  potential_x: number[];
  /** V(y) sampled on the y axis */
  potential_y: number[];
  energy: number;
  energy_x: number;
  energy_y: number;
  /** Physical quantum numbers of the state */
  label: number[];
  /** Names of those quantum numbers */
  quantum_numbers: string[];
  /** How many states share this energy */
  degeneracy: number;
  /** False if either axis had to be solved numerically */
  is_exact: boolean;
}
