/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { Grid2DSchema } from './grid2DSchema';
import type { PotentialSchema } from './potentialSchema';

/**
 * One eigenstate of a system that separates along x and y.

The potential is given per axis, so a 2D well is `infinite_well` on both
axes, an anisotropic trap is `harmonic` on both with different omega, and
the two axes may differ freely.
 */
export interface SeparableStateRequest {
  grid?: Grid2DSchema;
  potential_x: PotentialSchema;
  potential_y: PotentialSchema;
  /**
   * Index of the state along x, 0 being the ground state. This is a position in the ascending list of states, not the physical quantum number -- those differ per potential (a box starts at n=1, an oscillator at n=0) and are returned in `label`.
   * @minimum 0
   * @maximum 99
   */
  n1?: number;
  /**
   * Index of the state along y.
   * @minimum 0
   * @maximum 99
   */
  n2?: number;
  /**
   * States computed per axis that has no analytic solution.
   * @minimum 1
   * @maximum 100
   */
  n_states?: number;
}
