/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { SingleAtomStateResponsePositive } from './singleAtomStateResponsePositive';
import type { SingleAtomStateResponseNegative } from './singleAtomStateResponseNegative';

export interface SingleAtomStateResponse {
  positive: SingleAtomStateResponsePositive;
  negative: SingleAtomStateResponseNegative;
  bound_radius: number;
  Z: number;
  n: number;
  l: number;
  m: number;
}
