/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { SystemType } from './systemType';

/**
 * One subsystem, optionally repeated.

`copies` is a tensor product of *distinguishable* copies, so N spins are
`spin` with `copies = N`. Indistinguishable particles are a different
construction and are not reachable from here.
 */
export interface SystemSchema {
  type?: SystemType;
  /**
   * two_level gap
   */
  splitting?: number;
  /**
   * harmonic frequency
   */
  omega?: number;
  /**
   * spin quantum number j
   * @minimum 0
   */
  spin?: number;
  /**
   * rotor b
   */
  rotational_constant?: number;
  /**
   * ideal_gas particle count
   * @minimum 0
   */
  particles?: number;
  /**
   * ideal_gas volume
   */
  volume?: number;
  /**
   * @minimum 1
   * @maximum 5000
   */
  copies?: number;
}
