/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */

export interface TemperatureRange {
  /** */
  minimum?: number;
  /** */
  maximum?: number;
  /**
   * @minimum 2
   * @maximum 400
   */
  points?: number;
  logarithmic?: boolean;
}
