/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type { ThermodynamicsResponseMagnetisation } from './thermodynamicsResponseMagnetisation';
import type { ThermodynamicsResponseSusceptibility } from './thermodynamicsResponseSusceptibility';
import type { ThermodynamicsResponseVolume } from './thermodynamicsResponseVolume';
import type { ThermodynamicsResponseStates } from './thermodynamicsResponseStates';

/**
 * Everything one sweep yields, per temperature.

`potential_name` says which thermodynamic potential `potential` is: the
Helmholtz free energy canonically, the Gibbs energy once volume is free,
and so on. Both are floats, so reporting one as the other is an error
nothing downstream would catch.
 */
export interface ThermodynamicsResponse {
  temperatures: number[];
  energy: number[];
  heat_capacity: number[];
  entropy: number[];
  potential: number[];
  potential_name: string;
  magnetisation?: ThermodynamicsResponseMagnetisation;
  susceptibility?: ThermodynamicsResponseSusceptibility;
  volume?: ThermodynamicsResponseVolume;
  /** Total microstates, null if unbounded */
  states?: ThermodynamicsResponseStates;
}
