/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.2.2
 */
import type {
  CoexistenceRequest,
  CoexistenceResponse,
  GasRequest,
  GasResponse,
  GasSweepRequest,
  GasSweepResponse,
  HTTPValidationError,
  ThermodynamicsRequest,
  ThermodynamicsResponse
} from '.././schemas';

import { customFetch } from '../../http';

/**
 * Sweep a system in an ensemble over temperature.

The ensemble decides what is reported: a magnetic one adds the
magnetisation and its susceptibility, an isobaric one the mean volume.
Asking for a system the ensemble cannot be applied to -- a two-level
system in a magnetic field, whose levels carry no magnetisation -- is a
422 rather than a wrong number.
 * @summary Thermodynamics
 */
export type thermodynamicsV1StatphysThermodynamicsPostResponse200 = {
  data: ThermodynamicsResponse
  status: 200
}

export type thermodynamicsV1StatphysThermodynamicsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type thermodynamicsV1StatphysThermodynamicsPostResponseSuccess = (thermodynamicsV1StatphysThermodynamicsPostResponse200) & {
  headers: Headers;
};
export type thermodynamicsV1StatphysThermodynamicsPostResponseError = (thermodynamicsV1StatphysThermodynamicsPostResponse422) & {
  headers: Headers;
};

export type thermodynamicsV1StatphysThermodynamicsPostResponse = (thermodynamicsV1StatphysThermodynamicsPostResponseSuccess | thermodynamicsV1StatphysThermodynamicsPostResponseError)

export const getThermodynamicsV1StatphysThermodynamicsPostUrl = () => {


  

  return `/v1/statphys/thermodynamics`
}

export const thermodynamicsV1StatphysThermodynamicsPost = async (thermodynamicsRequest: ThermodynamicsRequest, options?: RequestInit): Promise<thermodynamicsV1StatphysThermodynamicsPostResponse> => {
  
  return customFetch<thermodynamicsV1StatphysThermodynamicsPostResponse>(getThermodynamicsV1StatphysThermodynamicsPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      thermodynamicsRequest,)
  }
);}


/**
 * Solid-gas equilibrium: `mu_crystal = mu_gas` gives the sublimation curve.

The crystal is `HarmonicMode(omega) ** 3` for the three modes of one atom,
times a single level at `-eps_c` for its binding -- log Z adds over blocks,
so that shift is exactly the `+beta eps_c` the energy carries. The gas is
an ideal gas, and equating the two chemical potentials closes it:

    P = (k_B T / Lambda^3) (1 - e^{-beta hbar omega})^3
        exp(-beta (eps_c - 3 hbar omega / 2))
 * @summary Coexistence
 */
export type coexistenceV1StatphysCoexistencePostResponse200 = {
  data: CoexistenceResponse
  status: 200
}

export type coexistenceV1StatphysCoexistencePostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type coexistenceV1StatphysCoexistencePostResponseSuccess = (coexistenceV1StatphysCoexistencePostResponse200) & {
  headers: Headers;
};
export type coexistenceV1StatphysCoexistencePostResponseError = (coexistenceV1StatphysCoexistencePostResponse422) & {
  headers: Headers;
};

export type coexistenceV1StatphysCoexistencePostResponse = (coexistenceV1StatphysCoexistencePostResponseSuccess | coexistenceV1StatphysCoexistencePostResponseError)

export const getCoexistenceV1StatphysCoexistencePostUrl = () => {


  

  return `/v1/statphys/coexistence`
}

export const coexistenceV1StatphysCoexistencePost = async (coexistenceRequest: CoexistenceRequest, options?: RequestInit): Promise<coexistenceV1StatphysCoexistencePostResponse> => {
  
  return customFetch<coexistenceV1StatphysCoexistencePostResponse>(getCoexistenceV1StatphysCoexistencePostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      coexistenceRequest,)
  }
);}


/**
 * Sample a gas of spin-`s` particles and fit its chemical potential.

Occupations are measured by Metropolis, averaged over orbitals of equal
energy, and fitted to the distribution with `mu` free. The exact `mu` is
solved separately and returned alongside, so the fit is checked rather
than trusted.
 * @summary Gas
 */
export type gasV1StatphysGasPostResponse200 = {
  data: GasResponse
  status: 200
}

export type gasV1StatphysGasPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type gasV1StatphysGasPostResponseSuccess = (gasV1StatphysGasPostResponse200) & {
  headers: Headers;
};
export type gasV1StatphysGasPostResponseError = (gasV1StatphysGasPostResponse422) & {
  headers: Headers;
};

export type gasV1StatphysGasPostResponse = (gasV1StatphysGasPostResponseSuccess | gasV1StatphysGasPostResponseError)

export const getGasV1StatphysGasPostUrl = () => {


  

  return `/v1/statphys/gas`
}

export const gasV1StatphysGasPost = async (gasRequest: GasRequest, options?: RequestInit): Promise<gasV1StatphysGasPostResponse> => {
  
  return customFetch<gasV1StatphysGasPostResponse>(getGasV1StatphysGasPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      gasRequest,)
  }
);}


/**
 * Converged chemical potential at every value of the swept parameter.

The points are independent, so they run in parallel processes -- one
request instead of a round trip per point, and wall time set by the
slowest point rather than their sum. Against them come the closed forms
the simulation never sees: Sommerfeld below the Fermi temperature and
Maxwell-Boltzmann above it, both for fermions only.
 * @summary Gas Sweep
 */
export type gasSweepV1StatphysGasSweepPostResponse200 = {
  data: GasSweepResponse
  status: 200
}

export type gasSweepV1StatphysGasSweepPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type gasSweepV1StatphysGasSweepPostResponseSuccess = (gasSweepV1StatphysGasSweepPostResponse200) & {
  headers: Headers;
};
export type gasSweepV1StatphysGasSweepPostResponseError = (gasSweepV1StatphysGasSweepPostResponse422) & {
  headers: Headers;
};

export type gasSweepV1StatphysGasSweepPostResponse = (gasSweepV1StatphysGasSweepPostResponseSuccess | gasSweepV1StatphysGasSweepPostResponseError)

export const getGasSweepV1StatphysGasSweepPostUrl = () => {


  

  return `/v1/statphys/gas-sweep`
}

export const gasSweepV1StatphysGasSweepPost = async (gasSweepRequest: GasSweepRequest, options?: RequestInit): Promise<gasSweepV1StatphysGasSweepPostResponse> => {
  
  return customFetch<gasSweepV1StatphysGasSweepPostResponse>(getGasSweepV1StatphysGasSweepPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      gasSweepRequest,)
  }
);}


